### ISSUE TITLE
filter out double mention at the beginning of toot

### ISSUE THREAD

**Issue by Hetti** [oe4dns/tootgroup.py#1]
If people put another same mention at the beginning of the toot, it should be filtered out.
Example: https://chaos.social/@metafunk/100577638047851199
should filter one of the two @metafunk mentions out

**Comment by oe4dns** [comment]
I was already thinking about filtering out the @mention completely but decided against it. It should only show as many @mentions as where in the original DM - will test and think about how to improve!

**Comment by oe4dns** [comment]
The mention is now completely filtered out in direct messages that will appear as genuine toots from the group.

Public mentions are just retootet - nothing can be changed in that case.
