### ISSUE TITLE
README.md: how to give _permission_ to a tootgroup

### ISSUE THREAD

**Issue by chri2** [oe4dns/tootgroup.py#11]
I didn't find any explanation how I can give access to an account to use a tootgroup.

From another issue I guessed that the account the tootgroup uses needs to follow the accounts that are allowed to use it.

If this is correct it would be nice to mention it in README.md.

**Comment by oe4dns** [comment]
True, this is an oversight that has never been mentioned. Will fix immediately

**Comment by oe4dns** [comment]
Done
