### ISSUE TITLE
feature request: approve note

### ISSUE THREAD

**Issue by chri2** [oe4dns/tootgroup.py#15]
It would be nice to have some kind of approval mechanism like:

* accountA toots a note to a tootgroup
* tootgroup toots that note to followers only with information that this is a request for approval
* if X (configurable number between 1 and number of actual number of followed-by) other followers approve the note by answering the note is tooted in public

This would make it possible to have some security that a toot through the group is at least prove read and approved by another group member.

**Comment by oe4dns** [comment]
Nice Idea, but I think this is out of scope. It would mean that a lot more state has to be kept on the server, probably needing a small database. In the current setup, offending accounts can be kicked out which I personally never had to, but is easy enough to do.

My great hope is that more or even all Fediverse tools support groups natively, just like Friendica, Lemmy and some others already do. This would make tootgroup.py redundant. But we're not even close to that yet, so I will of course keep updating tootgroup.

**Comment by chri2** [comment]
Yes, I thought about _state_ and just came up with an idea. Without deep knowledge of how the fediserver software works I would try it this way (if this is what servers support):

* accounts in the group need to follow the tootgroup account to get its boosts
* tootgroup boosts any new note to its followers only
* the accounts from the group consider the boost seeing from which account it came
* if a group member account agrees with publishing the content they _like_ the note
* the count of _likes by group accounts_ is the number that needs to be greater than the configured expected approvals

So the _approval state is saved in the likes_ of notes from group accounts.

The only bad thing is that tootgroup would have to look back in its notification for older notes.

This could be a configurable look-back period: if approval is used there's another configuration parameter valid like `lookback: 5d` meaning that tootgroup will be looking at notifications younger than 5 days. This would also be the period of time group members would have to approve notes.

Once re-tooted the tootgroup account itself likes the note it re-toots to remember that it already re-tooted it.

This would bring the overhead of reading the notification of the `lookback` period again and again, but it would also solve the #10 because we'd need to look at the timestamp of a notification instead of its ID.

**Comment by oe4dns** [comment]
I will have to think this through!
