### ISSUE TITLE
Hardcoded @metafunk

### ISSUE THREAD

**Issue by LongHairedHacker** [oe4dns/tootgroup.py#3]
Line 115 contains a hardcoded @metafunk as part of the regex.
I'd suggest generating it from the username in my_account.

https://github.com/oe4dns/tootgroup.py/blob/master/tootgroup.py#L115

**Comment by oe4dns** [comment]
Oh thanks! That is indeed a yet undetected bug. To my knowledte tootgroup.py only runs the @metafunk@chaos.social account and for that it works of course.

Will be fixed!

**Comment by oe4dns** [comment]
Fixed
