### ISSUE TITLE
Crashes if the group account never tooted anything

### ISSUE THREAD

**Issue by LongHairedHacker** [oe4dns/tootgroup.py#4]
`my_account["last_toot_time"]` is obtained by checking the last toot by the group account.

If the group account never tooted anything at all, `mastodon.account_statuses(my_account["id"])[0].created_at` will cause an index error at the first run of the tootgroup.py.

**Comment by oe4dns** [comment]
Thank you, will leave this open...
More (much more) Error Handling is already in the TODO list and I will make sure to check for this!

**Comment by oe4dns** [comment]
The code that was causing this issue has been removed in the meantime.
Issue will remain open anyway until it has been thoroughly tested.

**Comment by oe4dns** [comment]
Fixed in v0.8
