### ISSUE TITLE
How to set up when using 2FA?

### ISSUE THREAD

**Issue by MarkWieczorek** [oe4dns/tootgroup.py#8]
Is it possible to set up tootgroup when using 2FA? Disabled, tootgroup works fine, but when enabled, it doesn't recognize my password (as expected). I searched though the mastodon settings and couldn't find a way to set an app password, so: is this possible?

**Comment by oe4dns** [comment]
Never tried that because the usecase never came up. This shoudl be handled in the Mastdodon.py dependency. I will look into it.

**Comment by oe4dns** [comment]
tootgroup.py uses Mastodon.py underneath.

Mastodon.py's Readme states the following regarding the Login process:

`Note that this won’t work when using 2FA - you’ll have to use OAuth, in that case. To post, create an actual API instance:`

So unfortunately this does not work currently.

**Comment by oe4dns** [comment]
Cannot be implemented unless Mastodon.py supports this.
